Share modal
modrinth/omorphia pull request #74
Opened 2023-06-24 15:28 UTC by CodexAdrian

2023-06-24 15:40 UTC, triphora submitted a review, later dismissed

2023-06-24 15:40 UTC, triphora commented on lib/components/base/ShareModal.vue
> +    `https://mastodon.social/share?text=` +
mastodon.social isn't the only Mastodon instance. Needs to have a prompt to enter the instance to use.

2023-06-24 15:40 UTC, triphora commented on lib/components/base/ShareModal.vue
> +      'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=' +
Surely we don't need to use an external API for this. Quick google search returns https://github.com/cozmo/jsQR

2023-06-26 21:26 UTC, Geometrically requested changes
needs to be more padding here 
![image](https://github.com/modrinth/omorphia/assets/18202329/af572e42-b8a3-4880-a348-a4077f4fb1d5)


What does the clipboard button do?

![image](https://github.com/modrinth/omorphia/assets/18202329/4576a4bf-0312-4eda-9073-0eefba0a7b24)
This seems weird to style as an input, since you can't edit it.

The

2023-06-26 21:26 UTC, Geometrically commented on lib/components/base/ShareModal.vue
> +  padding: var(--gap-xl);
this is too much padding, see other modals for the correct amount

2023-06-26 21:26 UTC, Geometrically commented on docs/.vitepress/config.js
> +          { text: 'ShareModal', link: '/components/share-modal' },
this should be "Share Modal"

2023-06-28 15:44 UTC, merged